name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # バージョンタグの push でもトリガー

env:
  IMAGE_NAME: ghcr.io/oculora-project/oculora  # 個人アカウント用

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # コードをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # GitHub Container Registry にログイン
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: yunfie_twitter          # PAT 作成者の個人アカウント名
          password: ${{ secrets.CR_PAT }}   # Secrets に登録した Classic PAT

      # Docker イメージのビルドとタグ付け
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .
          if [[ "${{ github.event.ref_type }}" == "tag" ]]; then
            docker tag $IMAGE_NAME:latest $IMAGE_NAME:${{ github.ref_name }}
          fi

      # Docker イメージを push
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest
          if [[ "${{ github.event.ref_type }}" == "tag" ]]; then
            docker push $IMAGE_NAME:${{ github.ref_name }}
          fi
